### ISSUE TITLE
throw an exception when add a graph to a screen

### ISSUE THREAD

**Issue by LoveEachDay** [open-falcon/falcon-plus#109]
When I add a graph to a screen, after the submission, an exception is thrown:
```
暂时无法访问,请联系管理员.

error: {"error":"record not found"}


traceback日志如下:
Traceback (most recent call last):
  File "/data/falcon-plus/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/falcon-plus/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/falcon-plus/dashboard/rrd/view/dashboard/screen.py", line 176, in dash_graph_add
    timespan, graph_type, method, position)
  File "/data/falcon-plus/dashboard/rrd/model/graph.py", line 66, in add
    return graph_id and cls.get(graph_id)
  File "/data/falcon-plus/dashboard/rrd/model/graph.py", line 39, in get
    raise Exception(r.text)
Exception: {"error":"record not found"}
```

Actually the graph was added successfully.

**Comment by LoveEachDay** [comment]
I've upgrading falcon to v0.2 following the procedure in `http://www.jianshu.com/p/6fb2c2b4d030`.

**Comment by laiwei** [comment]
Is this error occurred every time or just one time?

Is there any screenshots?

**Comment by LoveEachDay** [comment]
It happens every time, and here's the procedure for reproducing:

1. add a screen
2. choose `+graph` in the screen page
3. fill in the form and submit

**Comment by LoveEachDay** [comment]
![image](https://cloud.githubusercontent.com/assets/1573213/26350007/43c71ec4-3fe4-11e7-9104-55c16f957bc7.png)

**Comment by laiwei** [comment]
I can not reproduce the problem .
Please make sure that you have the latest code.

If there is any further progress, just reopen this issue.

**Comment by laiwei** [comment]
@LoveEachDay
