### ISSUE TITLE
screen克隆报错，偶有成功

### ISSUE THREAD

**Issue by ijintong** [open-falcon/falcon-plus#202]
screen克隆时报错的提示如下，即使有这个报错，但也能成功克隆一张图表，但实际上有多张图表的。

暂时无法访问,请联系管理员。

Error: {"error":"record not found"}

Traceback:
Traceback (most recent call last):
  File "/opt/open-falcon/dashboard/env/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/open-falcon/dashboard/env/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/open-falcon/dashboard/rrd/view/dashboard/screen.py", line 64, in dash_screen_clone
    o.timespan, o.graph_type, o.method, o.position)
  File "/opt/open-falcon/dashboard/rrd/model/graph.py", line 66, in add
    return graph_id and cls.get(graph_id)
  File "/opt/open-falcon/dashboard/rrd/model/graph.py", line 39, in get
    raise Exception(r.text)
Exception: {"error":"record not found"}

**Comment by laiwei** [comment]
请使用最新版的api，已经在 https://github.com/open-falcon/falcon-plus/pull/186 修复了
