### ISSUE TITLE
新增screen报错

### ISSUE THREAD

**Issue by shuaifes** [open-falcon/falcon-plus#204]
Error: 404 page not found

Traceback:
Traceback (most recent call last):
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/work/open-falcon/dashboard/rrd/view/dashboard/screen.py", line 103, in dash_screen
    all_graphs.extend(generate_graph_urls(graph, start, end) or [])
  File "/home/work/open-falcon/dashboard/rrd/utils/graph_urls.py", line 18, in generate_graph_urls
    endpoint_objs = Endpoint.gets_by_endpoint(endpoint_list)
  File "/home/work/open-falcon/dashboard/rrd/model/endpoint.py", line 28, in gets_by_endpoint
    raise Exception(r.text)
Exception: 404 page not found

**Comment by laiwei** [comment]
请使用最新版本的api组件，在这个commit修复了 https://github.com/open-falcon/falcon-plus/commit/29f6b0046f8445ae6ad229d64b5c3b68747b7dda

**Comment by shuaifes** [comment]
我怎么可以在重新单独安装api组件@laiwei

**Comment by wangdi244** [comment]
重新打包之后，运行./falcon-api -c /usr/local/src/open-falcon/api/config/cfg.json，api服务起不来
报错：FATA[0000] db conn failed with error connect to falcon_portal: dial tcp 127.0.0.1:3306: getsockopt: connection refused，配置文件已经替换成本地环境的，不是127.0.0.1的ip

**Comment by laiwei** [comment]
@wangdi244  这里修改了一个配置中的错别字，参考一下这个issue： https://github.com/open-falcon/falcon-plus/issues/199
