### ISSUE TITLE
falcon-agent panic 

### ISSUE THREAD

**Issue by taomaree** [open-falcon/falcon-plus#240]
```
panic: runtime error: index out of range

goroutine 26 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux.MemInfo(0x18, 0xc42048fec0, 0x0)
	/root/go/src/github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux/meminfo.go:59 +0x569
github.com/open-falcon/falcon-plus/modules/agent/funcs.MemMetrics(0x7f64a0, 0xc42011f4d0, 0x86ded1)
	/root/go/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/meminfo.go:10 +0x37
github.com/open-falcon/falcon-plus/modules/agent/cron.collect(0x3c, 0xc42006e2a0, 0xb, 0xb)
	/root/go/src/github.com/open-falcon/falcon-plus/modules/agent/cron/collector.go:48 +0x128
created by github.com/open-falcon/falcon-plus/modules/agent/cron.Collect
	/root/go/src/github.com/open-falcon/falcon-plus/modules/agent/cron/collector.go:30 +0xb2
```

```
#uname -a
Linux host 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
#cat /etc/redhat-release
CentOS release 6.7 (Final)
#falcon-agent -v
5.1.2
```

**Comment by laiwei** [comment]
![image](https://user-images.githubusercontent.com/792850/30153732-1e652bb2-93ea-11e7-91f2-61a313c949b5.png)

可以修改下代码，把从/proc/meminfo中读出来的内容打印一下log吗？
