### ISSUE TITLE
ERROR, 在screen中添加新的graph时候，产生错误

### ISSUE THREAD

**Issue by YouZhengChuan** [open-falcon/falcon-plus#263]
# Error content
```
暂时无法访问,请联系管理员。

Error: {"error":"record not found"}


Traceback:
Traceback (most recent call last):
  File "/opt/apps/falcon-plus/dashboard/env/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/apps/falcon-plus/dashboard/env/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/apps/falcon-plus/dashboard/rrd/view/dashboard/screen.py", line 177, in dash_graph_add
    timespan, graph_type, method, position)
  File "/opt/apps/falcon-plus/dashboard/rrd/model/graph.py", line 66, in add
    return graph_id and cls.get(graph_id)
  File "/opt/apps/falcon-plus/dashboard/rrd/model/graph.py", line 39, in get
    raise Exception(r.text)
Exception: {"error":"record not found"}
```

# 截图信息
![image](https://user-images.githubusercontent.com/3882312/31042584-3a0dfeba-a5de-11e7-8498-c1327dbe0002.png)

**Comment by imzye** [comment]
可能是新添加的graph里面有些metric查询不到。

可以在已有的graph里面通过批量编辑，来添加

**Comment by laiwei** [comment]
请使用最新版本的api组件  @YouZhengChuan 

参考这个 https://github.com/open-falcon/falcon-plus/pull/186
