### ISSUE TITLE
dashboard点击Alarm-Dashboard报错

### ISSUE THREAD

**Issue by wpxdong** [open-falcon/falcon-plus#374]
Error: 'NoneType' object has no attribute 'cursor'

Traceback:
Traceback (most recent call last):
  File "/opt/open-falcon-v0.2.1/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/open-falcon-v0.2.1/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/open-falcon-v0.2.1/dashboard/rrd/view/portal/alarm.py", line 31, in alarm_dash_case_get
    cases, total = EventCase.query(page, limit, endpoint_q, metric_q, status)
  File "/opt/open-falcon-v0.2.1/dashboard/rrd/model/portal/alarm.py", line 90, in query
    vs = cls.select_vs(where=where, params=params, page=page, limit=limit, order='update_at desc')
  File "/opt/open-falcon-v0.2.1/dashboard/rrd/model/portal/bean.py", line 105, in select_vs
    rows = cls.select(where=where, params=params, order=order, limit=limit, page=page, offset=offset)
  File "/opt/open-falcon-v0.2.1/dashboard/rrd/model/portal/bean.py", line 101, in select
    return cls._db.query_all(sql, params)
  File "/opt/open-falcon-v0.2.1/dashboard/rrd/store.py", line 106, in query_all
    cursor = self.execute(*a, **kw)
  File "/opt/open-falcon-v0.2.1/dashboard/rrd/store.py", line 71, in execute
    cursor = self.get_conn().cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by yuline** [comment]
是不是alarm数据库地址配置的不对

**Comment by yuline** [comment]
是不是alarm数据库地址配置的不对

**Comment by wpxdong** [comment]
config.py里面的ALARM_DB_PASS忘记改了

**Comment by iceqing** [comment]
这个需要手工改这个文件dashbard/rrd/config.py

将一下信息替换为你的账户与密码

PORTAL_DB_USER = os.environ.get("PORTAL_DB_USER","账户")
PORTAL_DB_PASS = os.environ.get("PORTAL_DB_PASS","你的密码")

ALARM_DB_USER = os.environ.get("ALARM_DB_USER","账户")
ALARM_DB_PASS = os.environ.get("ALARM_DB_PASS","你的密码")
