### ISSUE TITLE
judge报错后自动重启

### ISSUE THREAD

**Issue by rogerwangcl** [open-falcon/falcon-plus#520]
- 组件：
  judge v0.2.0

- 日志:
```
2018/08/20 22:00:15 judge.go:47: [ERROR] parse func pdiff(#2） fail: strconv.Atoi: parsing "2\xef\xbc": invalid syntax. strategy id: 4023
2018/08/20 22:00:15 judge.go:47: [ERROR] parse func pdiff(#2） fail: strconv.Atoi: parsing "2\xef\xbc": invalid syntax. strategy id: 4023
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x742c56]

goroutine 86615156 [running]:
github.com/open-falcon/falcon-plus/modules/judge/store.(*SafeLinkedList).HistoryData(0xc42d7c4e00, 0xa, 0x801600, 0xc487cd7701, 0xc5d9b22db0, 0xc5e7c70688)
        /data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/linkedlist.go:81 +0x426
github.com/open-falcon/falcon-plus/modules/judge/store.AvgFunction.Compute(0x0, 0x0, 0xa, 0xc4b604f12c, 0x2, 0x4055400000000000, 0xc42d7c4e00, 0x411568, 0x70, 0xc5d9b22db0, ...)
        /data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/func.go:150 +0x3f
github.com/open-falcon/falcon-plus/modules/judge/store.(*AvgFunction).Compute(0xc5d9b22db0, 0xc42d7c4e00, 0xc4b604f12c, 0x2, 0x4055400000000000, 0x9f3240, 0xc5d9b22db0)
        <autogenerated>:12 +0x66
github.com/open-falcon/falcon-plus/modules/judge/store.judgeItemWithStrategy(0xc42d7c4e00, 0xb39, 0xc5a0d4b860, 0x12, 0xc55e705620, 0xc4b604f120, 0x8, 0xc4b604f12c, 0x2, 0x4055400000000000, ...)
        /data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:51 +0x205
github.com/open-falcon/falcon-plus/modules/judge/store.CheckStrategy(0xc42d7c4e00, 0xc4645b5ef0, 0x5b7ac970)
        /data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:40 +0x3cc
github.com/open-falcon/falcon-plus/modules/judge/store.Judge(0xc42d7c4e00, 0xc4645b5ef0, 0x5b7ac970)
        /data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:12 +0x3f
github.com/open-falcon/falcon-plus/modules/judge/store.(*JudgeItemMap).PushFrontAndMaintain(0xc42014e7e0, 0xc471bb2580, 0x20, 0xc4645b5ef0, 0xb, 0x5b7ac970)
        /data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/history.go:79 +0xa8
github.com/open-falcon/falcon-plus/modules/judge/rpc.(*Judge).Send(0xc4201425e8, 0xc52123a500, 0x99, 0x99, 0xc461dc7710, 0x0, 0x0)
        /data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/rpc/receiver.go:22 +0x10f
reflect.Value.call(0xc420150180, 0xc42014a058, 0x13, 0x8362bd, 0x4, 0xc5e7c70f20, 0x3, 0x3, 0xc4e96a4600, 0x100000000, ...)
        /data/service/go1.8.3/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc420150180, 0xc42014a058, 0x13, 0xc420559720, 0x3, 0x3, 0xa47498, 0xc420559768, 0xa47498)
        /data/service/go1.8.3/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc4201463c0, 0xc420069840, 0xc42c455398, 0xc42014c380, 0xc42b5f9f80, 0x79d540, 0xc56a104f20, 0x197, 0x7bf840, 0xc461dc7710, ...)
        /data/service/go1.8.3/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
        /data/service/go1.8.3/src/net/rpc/server.go:481 +0x404
2018/08/20 22:00:17 cfg.go:90: read config file: /data/service/of_service/judge.2/config/cfg.json successfully
2018/08/20 22:00:17 http.go:60: http listening 0.0.0.0:7081
2018/08/20 22:00:17 rpc.go:24: rpc listening 0.0.0.0:7080
2018/08/20 22:00:18 judge.go:47: [ERROR] parse func pdiff(#2） fail: strconv.Atoi: parsing "2\xef\xbc": invalid syntax. strategy id: 2397
```

**Comment by missuzhang** [comment]
不要用中文的标点符号,很明显你的）用的是中文 （golang都是utf8编码，一个中文占3个字节，所以字符串中1中文的长度是3）， 这样会导致judge判断字符串长度出现问题。
```
        idx := strings.Index(str, "#")
	args, err := atois(str[idx+1 : len(str)-1])
	if err != nil {
		return nil, err
	}
```
改成英文括号应该就好了。不过这里确实发现了一处代码不健壮，后续会体格pull request解决此问题。

**Comment by rogerwangcl** [comment]
```
2018/08/20 22:00:15 judge.go:47: [ERROR] parse func pdiff(#2） fail: strconv.Atoi: parsing "2\xef\xbc": invalid syntax. strategy id: 4023
2018/08/20 22:00:18 judge.go:47: [ERROR] parse func pdiff(#2） fail: strconv.Atoi: parsing "2\xef\xbc": invalid syntax. strategy id: 2397
```
这两个策略报错一直都在报，为什么没有一直重启，而是出现了上面的错误，我不认为是因为这两个策略配置有中文，引起的报错重启。

**Comment by MistShi** [comment]
@rogerwangcl 你是通过release的0.2.0的包进行部署的么？

**Comment by missuzhang** [comment]
确实不是这个引起的崩溃，昨天没仔细看，strconv 会返回error并不会引起crash。 主要原因是
```	diffVal := currentElement.Value.(*model.JudgeItem).Value - nextElement.Value.(*model.JudgeItem).Value1``` 
这里出现空指针了。底层实现list.List不是线程安全的，并且这里读取数据也没有加锁, 理论上存在执行到currentElement.Value或者nextElement.Value的时候，数据被清理的可能性。你这个崩溃后重启应该不是一直触发吧，偶然情况下触发的，频率高么？ 这个还需要做一些测试，如果确定是这个原因，那要改的代码还挺多。。。

**Comment by rogerwangcl** [comment]
@MistShi 是通过release的0.2.0的包进行部署的

**Comment by rogerwangcl** [comment]
@missuzhang 这是第一次遇到，之前有没有没注意到。

**Comment by missuzhang** [comment]
@rogerwangcl  额 走了一遍这附近的代码,触发这个bug实在是太极端了，堪比中彩票。
定位问题的过程如下：
1 分析了下源码，这地方空指针，肯定是有地方将list中的元素删除了。
2 judge删除list中元素的代码只有一处 ,linkedlist.go：**this.L.Remove(this.L.Back())**
```
// @return needJudge 如果是false不需要做judge，因为新上来的数据不合法
func (this *SafeLinkedList) PushFrontAndMaintain(v *model.JudgeItem, maxCount int) bool {
	this.Lock()
	defer this.Unlock()

	sz := this.L.Len()
	if sz > 0 {
		// 新push上来的数据有可能重复了，或者timestamp不对，这种数据要丢掉
		if v.Timestamp <= this.L.Front().Value.(*model.JudgeItem).Timestamp || v.Timestamp <= 0 {
			return false
		}
	}

	this.L.PushFront(v)

	sz++
	if sz <= maxCount {
		return true
	}

	del := sz - maxCount
	for i := 0; i < del; i++ {
		this.L.Remove(this.L.Back())
	}

	return true
}
```
3  只有一处问题就简单多了。这段逻辑的作用是，超过缓存数据最大数量（配置文件中的remain参数），将老数据丢弃。所以我们模拟当时的情况，在进入 currentElement.Value.(*model.JudgeItem).Value - nextElement.Value.(*model.JudgeItem).Value前将其中的数据删除：
具体做法就是：
3.1 写个测试用例模拟transfer发送3条初始数据，这时候执行这个测试里应该是成功的：
```
package store

import (
	"github.com/open-falcon/falcon-plus/common/model"
	"testing"
	"time"
)

func TestPDiffFunction_Compute(t *testing.T) {
	InitHistoryBigMap()
	now := time.Now().Unix()
	var mockItems []*model.JudgeItem
	for i := 0; i < 3; i++ {
		mockItems = append(mockItems, &model.JudgeItem{"mockEndopoint1", "cpu.idle",
			10, now - 7*24*60 - 60 + int64(i), "AVERAGE", make(map[string]string)})
	}

	pk := mockItems[0].PrimaryKey()

	for index := range mockItems {
		pk := mockItems[index].PrimaryKey()
		HistoryBigMap[pk[0:2]].PushFrontAndMaintain(pk, mockItems[index], 11, now)
	}
	L, _ := HistoryBigMap[pk[0:2]].Get(pk)
	fn := &PDiffFunction{Limit: 2, Operator: "=", RightValue: 0}
	fn.Compute(L)

}

```
![image](https://user-images.githubusercontent.com/14191268/44464101-6bbbdf80-a64c-11e8-8ae6-e8ddd6427800.png)

3.2 在 **currentElement.Value.(*model.JudgeItem).Value - nextElement.Value.(*model.JudgeItem).Value**之前之前插入一段代码，模拟push上来13（大于 remain -x（x为策略中pidff(#x) 中的值）条数据， 使**this.L.Remove(this.L.Back())** 触发。
```
                currentElement := firstElement
		func(){
			now := time.Now().Unix()
			var mockItems []*model.JudgeItem
			for i := 3; i < 16; i++ {
				mockItems = append(mockItems, &model.JudgeItem{"mockEndopoint1", "cpu.idle",
					10, now - 7*24*60 - 60 + int64(i), "AVERAGE", make(map[string]string)})
			}


			for index := range mockItems {
				pk := mockItems[index].PrimaryKey()
				HistoryBigMap[pk[0:2]].PushFrontAndMaintain(pk, mockItems[index], 11, now)
			}

		}()
		for i < limit {
			nextElement := currentElement.Next()
			diffVal := currentElement.Value.(*model.JudgeItem).Value - nextElement.Value.(*model.JudgeItem).Value
			diffTs := currentElement.Value.(*model.JudgeItem).Timestamp - nextElement.Value.(*model.JudgeItem).Timestamp
			vs[i] = &model.HistoryData{
				Timestamp: currentElement.Value.(*model.JudgeItem).Timestamp,
				Value:     diffVal / float64(diffTs),
			}
			i++
			currentElement = nextElement
		}
```
4 运行测试用例：

![image](https://user-images.githubusercontent.com/14191268/44464214-c35a4b00-a64c-11e8-967c-8af017b4d915.png)


目前没有发现其他触发的方式
这里确实隐藏了一个bug。触发这个bug的前提是，在代码刚好执行到
```
if size < limit+1 {
			isEnough = false
			limit = size - 1
		}
```
和
```
diffVal := currentElement.Value.(*model.JudgeItem).Value - nextElement.Value.(*model.JudgeItem).Value
```
之间的时候，push上来的数据至少应该是 remain - x(函数pidd(#x))个值，才会触发。

**Comment by rogerwangcl** [comment]
judge 重启后，重复发送 未恢复的报警，请问这个问题有什么方式解决吗？ 谢谢。

**Comment by YouZhengChuan** [comment]
我今天也遇到这个问题了，几率不高，上次出现这个bug的时候，还是去年10月份，但是出问题就崩溃了

**Comment by YouZhengChuan** [comment]
> judge

可以考虑二次开发，把告警状态在redis中进行维护。。
