### ISSUE TITLE
docker环境下新建模版中无法添加指标

### ISSUE THREAD

**Issue by wangxulong** [open-falcon/falcon-plus#522]
![image](https://user-images.githubusercontent.com/8357515/44566932-bb142400-a7a2-11e8-8d57-695ba68f3dc4.png)

**Comment by wangxulong** [comment]
单机部署服务正常
![image](https://user-images.githubusercontent.com/8357515/44568852-092d2580-a7ab-11e8-9464-af09e3c0a538.png)
面板的配置文件已经修改：
![image](https://user-images.githubusercontent.com/8357515/44568955-64f7ae80-a7ab-11e8-859a-401d0eea679b.png)

另外dashboard的镜像无法下载

**Comment by xueyunlong123** [comment]
@wangxulong 我和你遇到的问题一样。
1.dashboard的镜像无法下载的话，openfalcon/falcon-plus:v0.2.1，将镜像名改成这个就行了。
2.至于metric无法配置，我看docker日志
````
2018-08-27 06:22:23 ERROR:400:{"error":"open ./api/data/metric: no such file or directory"}
2018-08-27 06:22:23 ERROR:Exception on /api/metric/query [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 824, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/site-packages/werkzeug/test.py", line 854, in run_wsgi_app
    app_iter = app(environ, start_response)
TypeError: 'list' object is not callable
````
然后看了下源码：
![image](https://user-images.githubusercontent.com/12494617/44644395-7c7ea380-aa06-11e8-86ef-62f73e7f3071.png)
emmm，默认metric文件是有的，但是打开的时候报错了。打算自己手动build一下镜像试一下

**Comment by wbzqe** [comment]
你好，这个是api默认配置文件中的metric文件路径不对  ，修改为绝对路径，或者修改为bin目录下api可执行文件的相对路径即可~

**Comment by xueyunlong123** [comment]
@wbzqe 
nice.        
```
docker run -itd --name falcon-plus \
     --link=falcon-mysql:db.falcon \
     --link=falcon-redis:redis.falcon \
     -p 8433:8433 \
     -p 8080:8080 \
     -p 6030:6030 \
     -e MYSQL_PORT=root:yourpassword@tcp\(db.falcon:3306\) \
     -e REDIS_PORT=redis.falcon:6379  \
     -v /home/work/open-falcon/api/config:/open-falcon/api/config \
     -v /home/work/open-falcon/data:/open-falcon/data \
     -v /home/work/open-falcon/logs:/open-falcon/logs \
     openfalcon/falcon-plus:v0.2.1
```
宿主机添加文件：/home/work/open-falcon/api/config/cfg.json
```
{
    "log_level": "debug",
    "db": {
        "falcon_portal": "root:yourpassword@tcp(db.falcon:3306)/falcon_portal?charset=utf8&parseTime=True&loc=Local",
        "graph": "root:yourpassword@tcp(db.falcon:3306)/graph?charset=utf8&parseTime=True&loc=Local",
        "uic": "root:yourpassword@tcp(db.falcon:3306)/uic?charset=utf8&parseTime=True&loc=Local",
        "dashboard": "root:yourpassword@tcp(db.falcon:3306)/dashboard?charset=utf8&parseTime=True&loc=Local",
        "alarms": "root:yourpassword@tcp(db.falcon:3306)/alarms?charset=utf8&parseTime=True&loc=Local",
        "db_bug": true
    },
    "graphs": {
        "cluster": {
            "graph-00": "127.0.0.1:6070"
        },
        "max_conns": 100,
        "max_idle": 100,
        "conn_timeout": 1000,
        "call_timeout": 5000,
        "numberOfReplicas": 500
    },
    "metric_list_file": "./data/metric",
    "web_port": "0.0.0.0:8080",
    "access_control": true,
    "signup_disable": false,
    "salt": "",
    "skip_auth": false,
    "default_token": "default-token-used-in-server-side",
    "gen_doc": false,
    "gen_doc_path": "doc/module.html"
}
```

**Comment by laiwei** [comment]
- fixed at https://github.com/open-falcon/falcon-plus/pull/615
- download [latest docker image](https://hub.docker.com/r/openfalcon/falcon-plus/tags/)

@wangxulong @wbzqe 👍 

and same as https://github.com/open-falcon/falcon-plus/issues/611
