### ISSUE TITLE
请教个问题，以下模块报错是什么原因？

### ISSUE THREAD

**Issue by yang16889** [open-falcon/falcon-plus#561]
hostgroups/templates/等模块报错误，如下所示：

 
Temporary error,please contact your administrator.
Error: 'NoneType' object has no attribute 'cursor'
Traceback:
Traceback (most recent call last):
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/work/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/work/open-falcon/dashboard/rrd/view/portal/home.py", line 34, in home_get
    vs, total = HostGroup.query(page, limit, query, me)
  File "/home/work/open-falcon/dashboard/rrd/model/portal/host_group.py", line 62, in query
    vs = cls.select_vs(where=where, params=params, page=page, limit=limit, order='grp_name')
  File "/home/work/open-falcon/dashboard/rrd/model/portal/bean.py", line 105, in select_vs
    rows = cls.select(where=where, params=params, order=order, limit=limit, page=page, offset=offset)
  File "/home/work/open-falcon/dashboard/rrd/model/portal/bean.py", line 101, in select
    return cls._db.query_all(sql, params)
  File "/home/work/open-falcon/dashboard/rrd/store.py", line 106, in query_all
    cursor = self.execute(*a, **kw)
  File "/home/work/open-falcon/dashboard/rrd/store.py", line 71, in execute
    cursor = self.get_conn().cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by yang16889** [comment]
test

**Comment by MistShi** [comment]
@yang16889 检查一下数据库配置
