### ISSUE TITLE
judge 自动重启

### ISSUE THREAD

**Issue by visionguo** [open-falcon/falcon-plus#606]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x742c56]

goroutine 17542426 [running]:
github.com/open-falcon/falcon-plus/modules/judge/store.(*SafeLinkedList).HistoryData(0xc4534f4700, 0xa, 0x801600, 0xc5e6a5e501, 0xc5d7381350, 0xc42d167688)
/data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/linkedlist.go:81 +0x426
github.com/open-falcon/falcon-plus/modules/judge/store.AvgFunction.Compute(0x0, 0x0, 0xa, 0xc72501188c, 0x2, 0x4055400000000000, 0xc4534f4700, 0x411568, 0x70, 0xc5d7381350, ...)
/data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/func.go:150 +0x3f
github.com/open-falcon/falcon-plus/modules/judge/store.(*AvgFunction).Compute(0xc5d7381350, 0xc4534f4700, 0xc72501188c, 0x2, 0x4055400000000000, 0x9f3240, 0xc5d7381350)
:12 +0x66
github.com/open-falcon/falcon-plus/modules/judge/store.judgeItemWithStrategy(0xc4534f4700, 0xb38, 0xc64f3113e0, 0x11, 0xc4a5e038c0, 0xc725011880, 0x8, 0xc72501188c, 0x2, 0x4055400000000000, ...)
/data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:51 +0x205
github.com/open-falcon/falcon-plus/modules/judge/store.CheckStrategy(0xc4534f4700, 0xc68026ab90, 0x5bdd393c)
/data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:40 +0x3cc
github.com/open-falcon/falcon-plus/modules/judge/store.Judge(0xc4534f4700, 0xc68026ab90, 0x5bdd393c)
/data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:12 +0x3f
github.com/open-falcon/falcon-plus/modules/judge/store.(*JudgeItemMap).PushFrontAndMaintain(0xc42016d220, 0xc791847620, 0x20, 0xc68026ab90, 0xb, 0x5bdd393c)
/data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/store/history.go:79 +0xa8
github.com/open-falcon/falcon-plus/modules/judge/rpc.(*Judge).Send(0xc420128b28, 0xc55a451800, 0xc8, 0xc8, 0xc7697fdfa8, 0x0, 0x0)
/data/service/open-falcon/workspace/src/github.com/open-falcon/falcon-plus/modules/judge/rpc/receiver.go:22 +0x10f
reflect.Value.call(0xc4201347e0, 0xc42012a0e8, 0x13, 0x8362bd, 0x4, 0xc706e18f20, 0x3, 0x3, 0xc68342b680, 0x100000000, ...)
/data/service/go1.8.3/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc4201347e0, 0xc42012a0e8, 0x13, 0xc4201e8720, 0x3, 0x3, 0xa47498, 0xc4201e8768, 0xa47498)
/data/service/go1.8.3/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc42012ed00, 0xc42012e240, 0xc4279e6550, 0xc420130a80, 0xc421130c80, 0x79d540, 0xc65b293dc0, 0x197, 0x7bf840, 0xc7697fdfa8, ...)
/data/service/go1.8.3/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
/data/service/go1.8.3/src/net/rpc/server.go:481 +0x404

judge频繁重启，这是重启时的judge日志，大神给看看

**Comment by missuzhang** [comment]
https://github.com/open-falcon/falcon-plus/issues/520
你看看自己是不是重名的endpoint太多了才频繁的导致这个问题，最近比较忙就一直没有修。

**Comment by visionguo** [comment]
哦哦～
重名的endpoint太多了 是指的 endpoint_counter和tag_endpoint 么

**Comment by frieda1220** [comment]
尝试将agent 收集频率调整至10s一次，目前测试transfer  graph 都没有问题， 但是judge崩溃了， 报错也是上面的内容。请问 judge0.3tag中最小支持agent收集频率
