### ISSUE TITLE
alarm界面报错

### ISSUE THREAD

**Issue by alex1528** [open-falcon/falcon-plus#65]
```
暂时无法访问,请联系管理员.

error: 'NoneType' object has no attribute 'cursor'

traceback日志如下:
Traceback (most recent call last):
  File "/home/src/github.com/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/src/github.com/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/src/github.com/open-falcon/dashboard/rrd/view/portal/alarm.py", line 16, in alarm_dash_case_get
    cases, total = EventCase.query(page, limit, endpoint_q, metric_q, status)
  File "/home/src/github.com/open-falcon/dashboard/rrd/model/portal/alarm.py", line 75, in query
    vs = cls.select_vs(where=where, params=params, page=page, limit=limit, order='update_at desc')
  File "/home/src/github.com/open-falcon/dashboard/rrd/model/portal/bean.py", line 90, in select_vs
    rows = cls.select(where=where, params=params, order=order, limit=limit, page=page, offset=offset)
  File "/home/src/github.com/open-falcon/dashboard/rrd/model/portal/bean.py", line 86, in select
    return cls._db.query_all(sql, params)
  File "/home/src/github.com/open-falcon/dashboard/rrd/store.py", line 91, in query_all
    cursor = self.execute(*a, **kw)
  File "/home/src/github.com/open-falcon/dashboard/rrd/store.py", line 56, in execute
    cursor = self.get_conn().cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Comment by w675881684** [comment]
这个问题还存在啊


暂时无法访问,请联系管理员。

Error: 'NoneType' object has no attribute 'cursor'

Traceback:
Traceback (most recent call last):
  File "/root/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/open-falcon/dashboard/rrd/view/portal/alarm.py", line 31, in alarm_dash_case_get
    cases, total = EventCase.query(page, limit, endpoint_q, metric_q, status)
  File "/root/open-falcon/dashboard/rrd/model/portal/alarm.py", line 90, in query
    vs = cls.select_vs(where=where, params=params, page=page, limit=limit, order='update_at desc')
  File "/root/open-falcon/dashboard/rrd/model/portal/bean.py", line 105, in select_vs
    rows = cls.select(where=where, params=params, order=order, limit=limit, page=page, offset=offset)
  File "/root/open-falcon/dashboard/rrd/model/portal/bean.py", line 101, in select
    return cls._db.query_all(sql, params)
  File "/root/open-falcon/dashboard/rrd/store.py", line 106, in query_all
    cursor = self.execute(*a, **kw)
  File "/root/open-falcon/dashboard/rrd/store.py", line 71, in execute
    cursor = self.get_conn().cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by iceqing** [comment]
这个需要手工改这个文件dashbard/rrd/config.py

![image](https://user-images.githubusercontent.com/39587710/53084483-e7371480-353b-11e9-80a6-8f605bc1e525.png)
