### ISSUE TITLE
安装open-falcon客户端时报错“ImportError: No module named flask”

### ISSUE THREAD

**Issue by setamv** [open-falcon/falcon-plus#685]
按照帮助文档中“安装前段”一节内容操作（帮助文档连接https://book.open-falcon.org/zh_0_2/quick_install/frontend.html），在步骤“1.1.6. 以开发者模式启动”中，执行命令“./env/bin/python wsgi.py”报错了，错误如下：
Traceback (most recent call last):
  File "wsgi.py", line 28, in <module>
    from rrd import app
  File "/usr/local/open-falcon/dashboard/rrd/__init__.py", line 19, in <module>
    from flask import Flask, request
ImportError: No module named flask

请问这个要怎么解决呢？

**Comment by setamv** [comment]
已经解决了，是因为安装前端的过程中，有一个命令“./env/bin/pip install -r pip_requirements.txt -i https://pypi.douban.com/simple”执行报错导致的，原因是mysql需要安装所有的包，而我只安装了client和server，后面将mysql剩下的包也安装上，重新执行上述命令就OK了
