### ISSUE TITLE
[falcon judge panic] nil pointer dereference

### ISSUE THREAD

**Issue by YouZhengChuan** [open-falcon/falcon-plus#743]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7568c9]

goroutine 488390973 [running]:
github.com/open-falcon/falcon-plus/modules/judge/store.(*SafeLinkedList).HistoryData(0xc443fbd240, 0xa, 0x81c300, 0xc487850401, 0xc4d92e5230, 0xc4c08ad688)
	/GO/builds/github/src/github.com/open-falcon/falcon-plus/modules/judge/store/linkedlist.go:63 +0x1c9
github.com/open-falcon/falcon-plus/modules/judge/store.AllFunction.Compute(0x0, 0x0, 0xa, 0xc46e08d70c, 0x1, 0x4056800000000000, 0xc443fbd240, 0x411618, 0xc4d92e5230, 0x839580, ...)
	/GO/builds/github/src/github.com/open-falcon/falcon-plus/modules/judge/store/func.go:116 +0x42
github.com/open-falcon/falcon-plus/modules/judge/store.(*AllFunction).Compute(0xc4d92e5230, 0xc443fbd240, 0xc46e08d70c, 0x1, 0x4056800000000000, 0xa1b200, 0xc4d92e5230)
	<autogenerated>:10 +0x66
github.com/open-falcon/falcon-plus/modules/judge/store.judgeItemWithStrategy(0xc443fbd240, 0x15e, 0xc46e08d6d4, 0xc, 0xc4c8fe8090, 0xc46e08d700, 0x8, 0xc46e08d70c, 0x1, 0x4056800000000000, ...)
	/GO/builds/github/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:54 +0x205
github.com/open-falcon/falcon-plus/modules/judge/store.CheckStrategy(0xc443fbd240, 0xc4950413b0, 0x5cd4f23f)
	/GO/builds/github/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:43 +0x3cc
github.com/open-falcon/falcon-plus/modules/judge/store.Judge(0xc443fbd240, 0xc4950413b0, 0x5cd4f23f)
	/GO/builds/github/src/github.com/open-falcon/falcon-plus/modules/judge/store/judge.go:15 +0x3f
github.com/open-falcon/falcon-plus/modules/judge/store.(*JudgeItemMap).PushFrontAndMaintain(0xc42016fb20, 0xc48e777360, 0x20, 0xc4950413b0, 0xb, 0x5cd4f23f)
	/GO/builds/github/src/github.com/open-falcon/falcon-plus/modules/judge/store/history.go:79 +0xa8
github.com/open-falcon/falcon-plus/modules/judge/rpc.(*Judge).Send(0xc42012a060, 0xc437a70000, 0xc8, 0xc8, 0xc4f5442d90, 0x0, 0x0)
	/GO/builds/github/src/github.com/open-falcon/falcon-plus/modules/judge/rpc/receiver.go:22 +0x10f
reflect.Value.call(0xc42007c2a0, 0xc42000e050, 0x13, 0x852f45, 0x4, 0xc4c08adf20, 0x3, 0x3, 0x0, 0xa1b840, ...)
	/GO/builds/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc42007c2a0, 0xc42000e050, 0x13, 0xc48956f720, 0x3, 0x3, 0xc48956f718, 0x43e421, 0xc48faa0680)
	/GO/builds/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420122180, 0xc420122080, 0xc4512d7750, 0xc420082300, 0xc42a968ac0, 0x7b3c40, 0xc45b4ff3a0, 0x197, 0x7d72a0, 0xc4f5442d90, ...)
	/GO/builds/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
	/GO/builds/go/src/net/rpc/server.go:481 +0x404

**Comment by lts120784620** [comment]
当配置了一个counter类型指标的报警，最大报警次数超过remain限制的时候，judge会报空指针，进程crush
