### ISSUE TITLE
graph 内存问题

### ISSUE THREAD

**Issue by kanrin** [open-falcon/falcon-plus#764]
log如下
```
2019/06/26 07:14:06 cfg.go:90: g.ParseConfig ok, file /home/xxxx/open-falcon/graph/config/cfg.json
2019/06/26 07:14:06 db.go:26: g.InitDB ok
2019/06/26 07:14:06 rrdtool.go:55: rrdtool.Start ok
time="2019-06-26T07:14:06Z" level=debug msg="index.Start ok"
2019/06/26 07:14:06 main.go:22: 17052 register signal notify
2019/06/26 07:14:06 rpc.go:54: rpc.Start ok, listening on 0.0.0.0:6070
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x98672a, 0x16)
        /home/dc2-user/go/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc5ce900000, 0x100000, 0x7f63c37fdc00, 0xe23c58)
        /home/dc2-user/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0xe09300, 0x100000, 0x7f63a67171d0)
        /home/dc2-user/go/src/runtime/malloc.go:440 +0x374
runtime.(*mheap).grow(0xe09300, 0x1, 0x0)
        /home/dc2-user/go/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0xe09300, 0x1, 0x7f63c37fdce8)
        /home/dc2-user/go/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0xe09300, 0x1, 0x2, 0x7f63a6717218)
        /home/dc2-user/go/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
        /home/dc2-user/go/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7f63c37fdd58)
        /home/dc2-user/go/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0xe09300, 0x1, 0x10000000002, 0x7f63a67171d0)
        /home/dc2-user/go/src/runtime/mheap.go:628 +0xa0
runtime.(*mcentral).grow(0xe0a710, 0x0)
        /home/dc2-user/go/src/runtime/mcentral.go:212 +0x8e
runtime.(*mcentral).cacheSpan(0xe0a710, 0xc420021828)
        /home/dc2-user/go/src/runtime/mcentral.go:93 +0x12a
runtime.(*mcache).refill(0x7f63d4229960, 0xc500000002, 0xc5ce8e1fe4)
        /home/dc2-user/go/src/runtime/mcache.go:122 +0xa0
runtime.(*mcache).nextFree.func1()
        /home/dc2-user/go/src/runtime/malloc.go:538 +0x32
runtime.systemstack(0xc420021900)
        /home/dc2-user/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
        /home/dc2-user/go/src/runtime/proc.go:1132

goroutine 47182 [running]:
runtime.systemstack_switch()
        /home/dc2-user/go/src/runtime/asm_amd64.s:281 fp=0xc4204cb5e0 sp=0xc4204cb5d8
runtime.(*mcache).nextFree(0x7f63d4229960, 0xc4204cb602, 0x41464d, 0xc5ce8e1ff0, 0xc5ce8e1fe4)
        /home/dc2-user/go/src/runtime/malloc.go:539 +0xb9 fp=0xc4204cb638 sp=0xc4204cb5e0
runtime.mallocgc(0x10, 0x8c40c0, 0x7001, 0xc4204cb700)
        /home/dc2-user/go/src/runtime/malloc.go:691 +0x827 fp=0xc4204cb6d8 sp=0xc4204cb638
runtime.newobject(0x8c40c0, 0xc55045154b)
        /home/dc2-user/go/src/runtime/malloc.go:820 +0x38 fp=0xc4204cb708 sp=0xc4204cb6d8
reflect.unsafe_New(0x8c40c0, 0xc5ce8fc670)
        /home/dc2-user/go/src/runtime/malloc.go:825 +0x2b fp=0xc4204cb728 sp=0xc4204cb708
reflect.New(0xde2a20, 0x8c40c0, 0xc5ce8e1ff0, 0x198, 0xc5ce8e1ff0)
        /home/dc2-user/go/src/reflect/value.go:2138 +0x53 fp=0xc4204cb770 sp=0xc4204cb728
encoding/gob.allocValue(0xde2a20, 0x8c40c0, 0x8c40c0, 0x8c40c0, 0xc5ce8e1ff0)
        /home/dc2-user/go/src/encoding/gob/decode.go:1253 +0x35 fp=0xc4204cb7b0 sp=0xc4204cb770
encoding/gob.(*Decoder).decodeMap(0xc44c57ef00, 0xde2a20, 0x8ecc80, 0xc4395a1400, 0x8ecc80, 0xc5ce8e5220, 0x195, 0x99a2c8, 0x99a2c8, 0xdd6b80, ...)
        /home/dc2-user/go/src/encoding/gob/decode.go:573 +0x211 fp=0xc4204cb850 sp=0xc4204cb7b0
encoding/gob.(*Decoder).decOpFor.func2(0xc4303ec2b0, 0xc4395a1400, 0x8ecc80, 0xc5ce8e5220, 0x195)
        /home/dc2-user/go/src/encoding/gob/decode.go:826 +0x97 fp=0xc4204cb8b8 sp=0xc4204cb850
encoding/gob.(*Decoder).decodeStruct(0xc44c57ef00, 0xc4395a18c0, 0xc4201d2640, 0x9592c0, 0xc5ce8e5200, 0x199)
        /home/dc2-user/go/src/encoding/gob/decode.go:475 +0x17e fp=0xc4204cb948 sp=0xc4204cb8b8
encoding/gob.(*Decoder).decOpFor.func4(0xc5ce8c6c00, 0xc4395a13e0, 0x9592c0, 0xc5ce8e5200, 0x199)
        /home/dc2-user/go/src/encoding/gob/decode.go:857 +0x5d fp=0xc4204cb988 sp=0xc4204cb948
encoding/gob.(*Decoder).decodeArrayHelper(0xc44c57ef00, 0xc4395a13e0, 0x8b7e80, 0xc5ce8a16a0, 0x197, 0xc4395a1bc0, 0x66, 0xdd6b80, 0xc4360a16f0, 0x0)
        /home/dc2-user/go/src/encoding/gob/decode.go:534 +0x1d9 fp=0xc4204cba08 sp=0xc4204cb988
encoding/gob.(*Decoder).decodeSlice(0xc44c57ef00, 0xc4395a13e0, 0x8b7e80, 0xc5ce8a16a0, 0x197, 0xc4395a1bc0, 0xdd6b80, 0xc4360a16f0, 0x0)
        /home/dc2-user/go/src/encoding/gob/decode.go:627 +0x302 fp=0xc4204cbac8 sp=0xc4204cba08
encoding/gob.(*Decoder).decOpFor.func3(0xc430709380, 0xc4395a13e0, 0x8b7e80, 0xc5ce8a16a0, 0x197)
        /home/dc2-user/go/src/encoding/gob/decode.go:845 +0x78 fp=0xc4204cbb20 sp=0xc4204cbac8
encoding/gob.(*Decoder).decodeSingle(0xc44c57ef00, 0xc4395a1860, 0xc4201d2580, 0x8b7e80, 0xc5ce8a16a0, 0x197)
        /home/dc2-user/go/src/encoding/gob/decode.go:441 +0x102 fp=0xc4204cbb68 sp=0xc4204cbb20
encoding/gob.(*Decoder).decodeValue(0xc44c57ef00, 0x46, 0x8b7e80, 0xc5ce8a16a0, 0x197)
        /home/dc2-user/go/src/encoding/gob/decode.go:1202 +0x208 fp=0xc4204cbbf8 sp=0xc4204cbb68
encoding/gob.(*Decoder).DecodeValue(0xc44c57ef00, 0xc4201d2440, 0xc5ce8a16a0, 0x16, 0x0, 0x0)
        /home/dc2-user/go/src/encoding/gob/decoder.go:210 +0x147 fp=0xc4204cbc38 sp=0xc4204cbbf8
encoding/gob.(*Decoder).Decode(0xc44c57ef00, 0xc4201d2440, 0xc5ce8a16a0, 0xc4201d2440, 0xc5ce8a16a0)
        /home/dc2-user/go/src/encoding/gob/decoder.go:185 +0x16d fp=0xc4204cbc98 sp=0xc4204cbc38
net/rpc.(*gobServerCodec).ReadRequestBody(0xc454435ec0, 0xc4201d2440, 0xc5ce8a16a0, 0xc4201d2440, 0xc5ce8a16a0)
        /home/dc2-user/go/src/net/rpc/server.go:411 +0x43 fp=0xc4204cbcd0 sp=0xc4204cbc98
net/rpc.(*Server).readRequest(0xc4201f4380, 0xddd3c0, 0xc454435ec0, 0xc4201f4380, 0xc435e2af68, 0xc4201dc700, 0xc4202ee060, 0x8b7e80, 0xc5ce6d9d80, 0x197, ...)
        /home/dc2-user/go/src/net/rpc/server.go:566 +0x2cb fp=0xc4204cbd78 sp=0xc4204cbcd0
net/rpc.(*Server).ServeCodec(0xc4201f4380, 0xddd3c0, 0xc454435ec0)
        /home/dc2-user/go/src/net/rpc/server.go:466 +0x77 fp=0xc4204cbe68 sp=0xc4204cbd78
net/rpc.(*Server).ServeConn(0xc4201f4380, 0x7f63d4189000, 0xc420276050)
        /home/dc2-user/go/src/net/rpc/server.go:458 +0x373 fp=0xc4204cbf68 sp=0xc4204cbe68
net/rpc.ServeConn(0x7f63d4189000, 0xc420276050)
        /home/dc2-user/go/src/net/rpc/server.go:663 +0x41 fp=0xc4204cbf90 sp=0xc4204cbf68
github.com/open-falcon/falcon-plus/modules/graph/api.Start.func1.1(0xddf8a0, 0xc420276050)
        /home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/graph/api/rpc.go:79 +0xb3 fp=0xc4204cbfd0 sp=0xc4204cbf90
runtime.goexit()
        /home/dc2-user/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4204cbfd8 sp=0xc4204cbfd0
created by github.com/open-falcon/falcon-plus/modules/graph/api.Start.func1
        /home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/graph/api/rpc.go:80 +0xa6
```

**Comment by laiwei** [comment]
应该是 counter 数量太多，超过本机的物理内存了。

参考 https://book.open-falcon.org/zh_0_2/practice/deploy.html 这里的内存使用预估

![image](https://user-images.githubusercontent.com/792850/60558252-16c41c00-9d7b-11e9-8693-71fb27f27558.png)
