### ISSUE TITLE
启动前端提示错误：falcon-dashboard started..., pid=cat: var/app.pid: No such file or directory

### ISSUE THREAD

**Issue by jinteng123** [open-falcon/falcon-plus#802]

**Comment by chaiqinghu** [comment]
我也遇到了相同的问题 ，我的日志内容为
`2019-09-05 15:43:17 +0000] [59786] [INFO] Starting gunicorn 19.9.0
[2019-09-05 15:43:17 +0000] [59786] [INFO] Listening at: http://0.0.0.0:8081 (59786)
[2019-09-05 15:43:17 +0000] [59786] [INFO] Using worker: sync
[2019-09-05 15:43:17 +0000] [59792] [INFO] Booting worker with pid: 59792
[2019-09-05 15:43:17 +0000] [59792] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/local/open-falcon/dashboard/wsgi.py", line 28, in <module>
    from rrd import app
  File "/usr/local/open-falcon/dashboard/rrd/__init__.py", line 19, in <module>
    from flask import Flask, request
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables (routing.py, line 948)
[2019-09-05 15:43:17 +0000] [59792] [INFO] Worker exiting (pid: 59792)
[2019-09-05 15:43:17 +0000] [59786] [INFO] Shutting down: Master
[2019-09-05 15:43:17 +0000] [59786] [INFO] Reason: Worker failed to boot.

`

**Comment by Dollyn** [comment]
同样的问题

**Comment by Dollyn** [comment]
只能用python2，又不支持python3， python2还报错

**Comment by laiwei** [comment]
fixed https://github.com/open-falcon/dashboard/pull/140  @jinteng123 @Dollyn

**Comment by cui-github** [comment]
解决了吗

**Comment by cui-github** [comment]
启动openfalcon 的dashboard 服务时，出现错误；
falcon-dashboard started..., pid=cat: var/app.pid: No such file or directory

报错日志是：

[2019-10-30 11:39:58 +0800] [5506] [INFO] Starting gunicorn 19.9.0
[2019-10-30 11:39:58 +0800] [5506] [INFO] Listening at: http://192.168.8.39:8082 (5506)
[2019-10-30 11:39:58 +0800] [5506] [INFO] Using worker: sync
[2019-10-30 11:39:58 +0800] [5510] [INFO] Booting worker with pid: 5510
[2019-10-30 11:39:58 +0800] [5510] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/open-falcon/dashboard/env/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/open-falcon/dashboard/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/open-falcon/dashboard/env/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/open-falcon/dashboard/env/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/open-falcon/dashboard/env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/open-falcon/dashboard/env/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/open-falcon/dashboard/env/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/open-falcon/dashboard/wsgi.py", line 23
    print "running without local python env"
                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("running without local python env")?
[2019-10-30 11:39:58 +0800] [5510] [INFO] Worker exiting (pid: 5510)
[2019-10-30 11:39:58 +0800] [5506] [INFO] Shutting down: Master
[2019-10-30 11:39:58 +0800] [5506] [INFO] Reason: Worker failed to boot.
求大佬解决，十万分感谢。

**Comment by cui-github** [comment]
> 我也遇到了相同的问题 ，我的日志内容为
> `2019-09-05 15:43:17 +0000] [59786] [INFO] Starting gunicorn 19.9.0
> [2019-09-05 15:43:17 +0000] [59786] [INFO] Listening at: http://0.0.0.0:8081 (59786)
> [2019-09-05 15:43:17 +0000] [59786] [INFO] Using worker: sync
> [2019-09-05 15:43:17 +0000] [59792] [INFO] Booting worker with pid: 59792
> [2019-09-05 15:43:17 +0000] [59792] [ERROR] Exception in worker process
> Traceback (most recent call last):
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
> worker.init_process()
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
> self.load_wsgi()
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
> self.wsgi = self.app.wsgi()
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
> self.callable = self.load()
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
> return self.load_wsgiapp()
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
> return util.import_app(self.app_uri)
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
> **import**(module)
> File "/usr/local/open-falcon/dashboard/wsgi.py", line 28, in
> from rrd import app
> File "/usr/local/open-falcon/dashboard/rrd/**init**.py", line 19, in
> from flask import Flask, request
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/**init**.py", line 21, in
> from .app import Flask, Request, Response
> File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 23, in
> from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
> SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables (routing.py, line 948)
> [2019-09-05 15:43:17 +0000] [59792] [INFO] Worker exiting (pid: 59792)
> [2019-09-05 15:43:17 +0000] [59786] [INFO] Shutting down: Master
> [2019-09-05 15:43:17 +0000] [59786] [INFO] Reason: Worker failed to boot.
> 
> `

哈喽  你的问题解决了吗  我也遇到了这个问题，麻烦告诉我是咋解决的吗

**Comment by loveAhQ** [comment]
> > 我也遇到了相同的问题 ，我的日志内容为
> > `2019-09-05 15:43:17 +0000] [59786] [INFO] Starting gunicorn 19.9.0
> > [2019-09-05 15:43:17 +0000] [59786] [INFO] Listening at: http://0.0.0.0:8081 (59786)
> > [2019-09-05 15:43:17 +0000] [59786] [INFO] Using worker: sync
> > [2019-09-05 15:43:17 +0000] [59792] [INFO] Booting worker with pid: 59792
> > [2019-09-05 15:43:17 +0000] [59792] [ERROR] Exception in worker process
> > Traceback (most recent call last):
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
> > worker.init_process()
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
> > self.load_wsgi()
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
> > self.wsgi = self.app.wsgi()
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
> > self.callable = self.load()
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
> > return self.load_wsgiapp()
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
> > return util.import_app(self.app_uri)
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
> > **import**(module)
> > File "/usr/local/open-falcon/dashboard/wsgi.py", line 28, in
> > from rrd import app
> > File "/usr/local/open-falcon/dashboard/rrd/**init**.py", line 19, in
> > from flask import Flask, request
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/**init**.py", line 21, in
> > from .app import Flask, Request, Response
> > File "/usr/local/open-falcon/dashboard/env/lib/python2.7/site-packages/flask/app.py", line 23, in
> > from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
> > SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables (routing.py, line 948)
> > [2019-09-05 15:43:17 +0000] [59792] [INFO] Worker exiting (pid: 59792)
> > [2019-09-05 15:43:17 +0000] [59786] [INFO] Shutting down: Master
> > [2019-09-05 15:43:17 +0000] [59786] [INFO] Reason: Worker failed to boot.
> > `
> 
> 哈喽 你的问题解决了吗 我也遇到了这个问题，麻烦告诉我是咋解决的吗

我是把python升级从2.6到2.7后就可以了
