### ISSUE TITLE
请教大佬Centos8部署falcon-agent启动后报错。无法启动采集agent。日志报错内容如下，网上看有人遇到同样问题，说不支持centos8

### ISSUE THREAD

**Issue by zjj353533004** [open-falcon/falcon-plus#952]
2022/02/26 17:01:37 cfg.go:142: read config file: cfg.json successfully
2022/02/26 17:01:37 http.go:88: listening :1988
panic: runtime error: index out of range

goroutine 15 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux.SocketStatSummary(0xc000030000, 0x50, 0x48)
  /home/work/gopath/src/github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux/ss_s.go:49 +0x766
github.com/open-falcon/falcon-plus/modules/agent/funcs.SocketStatSummaryMetrics(0x0, 0x0, 0x0)
  /home/work/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/sockstat.go:24 +0x37
github.com/open-falcon/falcon-plus/modules/agent/cron.collect(0x3c, 0xc0000fe1c0, 0x2, 0x2)
  /home/work/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/cron/collector.go:63 +0x14d
created by github.com/open-falcon/falcon-plus/modules/agent/cron.Collect
  /home/work/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/cron/collector.go:44 +0xbf

**Comment by kingte11056** [comment]
同问  目前的主机是 Ubuntu20.04

**Comment by kingte11056** [comment]
主机版本回退到 ubuntu-18.04 可以运行了  就是和主机相关的bug

**Comment by zjj353533004** [comment]
已经升级到n9e夜莺监控系统了，使用telegraf采集，也挺好用的

**Comment by signmem** [comment]
*  尝试用 go-1.18 编译， 我没有遇到问题  
*  另外  vendor/github.com/toolkits/nux/ss_s.go  这个代码有问题的     
* 当服务器 slab 过大时候，这个 ss_s.go 搜集数据时会导致服务器卡顿问题的。。必须重构
